### ISSUE TITLE
On Chrome for mobile, the click event triggers event if element was created after the pointerup event

### ISSUE THREAD

**Issue by fromi** [minwork/react#10]
I use use-long-press to implement this features:

- open a dialog box on a short click to show & explain the options
- play the default option on a long click

The dialog box has a backdrop. When the backdrop is clicked, the dialog is closed.

I works fine **except for Chrome on mobile devices**. I that case, a short click produces this behavior:

1. pointer up, cancel reason is "CancelledByRelease", open the dialog box.
2. if the pointer is on the backdrop, Chrome fires the "pointer click": dialog is immediately closed.

A workaround:
```
  const clicked = useRef(false)

  const bind = useLongPress(() => /* whatever long press does */, {
    onCancel: (event, { reason }) => {
      if (reason === LongPressCallbackReason.CancelledByRelease) {
        clicked.current = true
      }
    }
  })
  
  const onClick = useCallback(() => {
    if (clicked.current) {
      clicked.current = false
      /* whatever short press does */
    }
  }, [])
  
  return <div ref={ref} onClick={onClick} {...bind()}/>
```

Maybe use-long-press could evolve to offer this workaround or something similar? It was painful to sort out.

**Comment by minwork** [comment]
Hey @fromi do I understand correctly that Chrome on mobile triggers events in such a sequence that cause dialog to immediately close (pointerUp then click)? If that's the case wouldn't it be sufficient to just trigger `onClick` handler when cancel reason is `LongPressCallbackReason.CancelledByRelease` instead of adding `onClick` beside binding long press?

```tsx
const onClick = useCallback(() => {
      /* whatever short press does */
  }, [])

const bind = useLongPress(() => /* whatever long press does */, {
    onCancel: (event, { reason }) => {
      if (reason === LongPressCallbackReason.CancelledByRelease) {
        onClick()
      }
    }
  })
  
  return <div ref={ref} {...bind()}/>
```

I suspect this behaviour may be caused by simulating click events when using touch device which I've encountered before. 
Generally, if you want to handle both _click_ and _long press_ events on some element `onCancel` should suffice to handle that, because then you are sure that you either call _long press_ callback or _click_ callback, not both.

**Comment by fromi** [comment]
Hi,

No, it does not work, because the component that handles a long & short click is a completely different component than the dialog that closes on the backdrop click :
if I call "onClick()" inside the "onCancel" callback, then the dialog opens immediately on the "pointer up" event (the event that trigger "onCancel" here). And the "onClick" event lands on the dialog backdrop on Chrome for mobile (event though the dialog did not exists when "pointer up" event was triggered!).

However, here is another (more hacky?) workaround:
```
const bind = useLongPress(() => /* whatever long press does */, {
    onCancel: (event, { reason }) => {
      if (reason === LongPressCallbackReason.CancelledByRelease) {
        setTimeout(() => openDialog())
      }
    }
  })
```
With a very short timeout, the onClick event happens before the dialog is opened...

**Comment by minwork** [comment]
Do you observe same behaviour when using `detect: 'mouse'` or `detect: 'touch'`?

**Comment by fromi** [comment]
> Do you observe same behaviour when using `detect: 'mouse'` or `detect: 'touch'`?

- detect: LongPressEventType.Mouse
This fixes everything, at least on Chrome... However, will other browsers for touch screens work too?

- detect: LongPressEventType.Touch
Same behavior on Chrome mobile + feature no longer work on desktop.

**Comment by minwork** [comment]
> detect: LongPressEventType.Mouse
This fixes everything, at least on Chrome... However, will other browsers for touch screens work too?

Not sure.

I have one more idea which may work - have you tried calling `event.stopPropagation()`? I can't tell for sure but it seems that click is propagating up which is why newly opened dialog receives click on the backdrop after opening it from long press callback. Maybe if you try calling `event.stopPropagation()` or `event.nativeEvent.stopPropagation()` inside `onStart` or directly on element `onClick`, `onPointerDown` or `onPointerDownCapture` it may prevent click to pass to dialog backdrop. It would be the best to check where in DOM backdrop is created and what is the exact sequence of events to pinpoint the exact events sequence leading to this behaviour.

**Comment by fromi** [comment]
Hi, event.stopPropagation() does not work. The click actually directly lands on the dialog backdrop, it is not triggered at all on the other component (covered by the backdrop). The dialog is not a dom ancestor of the component either, so propagation is not at stakes here.
To me, it is a bug / strange implementation of Chrome. You can either offer a workaround, or just leave this thread as an answered question which might help other developers facing the same issue than me.

**Comment by minwork** [comment]
Hey, thanks for letting me know. I don't want to introduce any situational workarounds directly into the library code so I will leave it as an answered question as you suggested.

**Comment by cpojer** [comment]
I ran into the same issue. I built a `usePress` hook to wrap `useLongPress` for this use case: https://gist.github.com/cpojer/641bf305e6185006ea453e7631b80f95

Usage:
```ts
const props = usePress({
    onLongPress,
    onPress: onClick,
  })();
```

**Comment by minwork** [comment]
minwork/use-long-press#5 also exposed some unexpected Chrome behaviour in handling mouse and touch events, so I'm leaving it as a reference.
