### ISSUE TITLE
[QUESTION]How to avoid children triger onClick when longPress is trigger?

### ISSUE THREAD

**Issue by xmsz-stu** [minwork/react#39]
```
<div onLongPress={()=>{console.log(2)}}>
   <div onClick={()=>{console.log(1)}}>children</div>
</div>

```

When trigger longpress，the children still trigger onClick? how can i avoid this?

**Comment by minwork** [comment]
I assume it is because of event propagation. 

When clicking children you also "click" its container. If you want to be able to detect click only on children without triggering long press on container you need to call `event.stopPropagation()` on children (in `onClick` handler or if that not work then `onMouseDown` / `onTouchStart` / `onPointerDown` depending on `detect` param value)

So for example:

```tsx
<div onLongPress={()=>{console.log(2)}}>
   <div onClick={(event)=>{ event.stopPropagation(); console.log(1)}}>children</div>
</div>
```
