### ISSUE TITLE
useLongPress: Cancel when multiple touches occur

### ISSUE THREAD

**Issue by aeharding** [minwork/react#42]
Hi! Thanks for the useLongPress hook. I like it a lot. I just noticed a difference between this library and iOS's native long press, so I thought I would make this issue.

----

## Problem

On native iOS, if a second touch starts before the long press finishes, the long press is cancelled.

This can be observed in the native iOS Mail app by simply putting on finger down, and then placing another finger before the long press has a chance to fire.

This is important for accessibility reasons (see: https://github.com/aeharding/voyager/issues/1254).

## Proposed Solution

I would like to see an extra option, `cancelOnTouches` (or something like that) where any time multiple touches occur, the long press is cancelled.

**Comment by minwork** [comment]
Hey @aeharding, thanks for sharing this use case. 
I don't plan on adding new option specifically for handling this case as it is too specific BUT it can be addressed right now and I may add one feature that could make it easier in the future (but I can't promise you that).

Right now, assuming you are using `detect: LongPressEventType.Touch`, in order to handle it you need to extract `cancel` trigger from `bind` result and call it when you detect second touch in `onTouchStart`: 

```tsx
// ...
const bind = useLongPress(/* ... */);
const { onTouchStart, onTouchMove, onTouchEnd } = bind(/* optional context */);
const handleTouchStart = useCallback<TouchEventHandler>(event => {
  // Your custom logic to detect second touch
 if (/* second touch */) {
  // Trigger long press cancel
  onTouchEnd();
 } else {
  onTouchStart();
 }
}, []);

// ...
return <div onTouchStart={handleTouchStart} onTouchMove={onTouchMove} onTouchEnd={onTouchEnd}>{/* ... */}</div>;
```
